[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}\
- {{ commit.message | upper_first | trim }} \
([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/zeroseven/pagebased/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}\n
"""
footer = ""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
    { message = "^\\[!!!\\]", group = "⚠ Breaking Changes" },
    { message = "^\\[FEATURE\\]", group = "Features" },
    { message = "^\\[BUGFIX\\]", group = "Bug Fixes" },
    { message = "^\\[SECURITY\\]", group = "Security" },
    { message = "^\\[TASK\\]", group = "Tasks" },
    { message = "^\\[DOCS\\]", group = "Documentation" },
    { message = "^Merge", skip = true },
    { message = ".*", group = "Other" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
