name: ddev-pagebased
services:
  db:
    build:
      context: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.25.1
        gid: "20"
        uid: "502"
        username: jenss
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-pagebased-db
    environment:
      BITNAMI_VOLUME_DIR: ""
      COLUMNS: "80"
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "20"
      DDEV_GOARCH: arm64
      DDEV_GOOS: darwin
      DDEV_HOSTNAME: pagebased.ddev.site
      DDEV_PHP_VERSION: "8.1"
      DDEV_PRIMARY_URL: https://pagebased.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://pagebased.ddev.site
      DDEV_PROJECT: pagebased
      DDEV_PROJECT_TYPE: typo3
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: pagebased
      DDEV_TLD: ddev.site
      DDEV_UID: "502"
      DDEV_USER: jenss
      DDEV_VERSION: v1.25.1
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: ""
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/pagebased-db/mysql_history
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Europe/Berlin
      USER: jenss
    hostname: pagebased-db
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mariadb-10.11:v1.25.1-pagebased-built
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased
      com.ddev.platform: ddev
      com.ddev.site-name: pagebased
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: "502:20"
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.ddev
        target: /mnt/ddev_config
        bind: {}
      - type: bind
        source: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.ddev/db_snapshots
        target: /mnt/snapshots
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/jenss
  web:
    build:
      context: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:v1.25.1
        DDEV_DATABASE: mariadb:10.11
        DDEV_PHP_VERSION: "8.1"
        gid: "20"
        uid: "502"
        username: jenss
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-pagebased-web
    environment:
      COLUMNS: "80"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: .build/public
      DDEV_FILES_DIR: /var/www/html/.build/public/fileadmin
      DDEV_FILES_DIRS: /var/www/html/.build/public/fileadmin
      DDEV_GID: "20"
      DDEV_GOARCH: arm64
      DDEV_GOOS: darwin
      DDEV_HOSTNAME: pagebased.ddev.site
      DDEV_MUTAGEN_ENABLED: "true"
      DDEV_PHP_VERSION: "8.1"
      DDEV_PRIMARY_URL: https://pagebased.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://pagebased.ddev.site
      DDEV_PROJECT: pagebased
      DDEV_PROJECT_TYPE: typo3
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: pagebased
      DDEV_TLD: ddev.site
      DDEV_UID: "502"
      DDEV_USER: jenss
      DDEV_VERSION: v1.25.1
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: xhgui
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: .build/public
      DRUSH_OPTIONS_URI: https://pagebased.ddev.site
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/pagebased-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=pagebased.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "115"
      TYPO3_CONTEXT: Development/DDEV
      TYPO3_PATH_APP: /var/www/html/.build
      TZ: Europe/Berlin
      USER: jenss
      VIRTUAL_HOST: pagebased.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
      typo3DatabaseHost: db
      typo3DatabaseName: db
      typo3DatabasePassword: root
      typo3DatabaseUsername: root
    hostname: pagebased-web
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-webserver:v1.25.1-pagebased-built
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased
      com.ddev.platform: ddev
      com.ddev.site-name: pagebased
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: "502:20"
    volumes:
      - type: volume
        source: project_mutagen
        target: /var/www
        volume:
          nocopy: true
      - type: volume
        source: project_mutagen
        target: /tmp/project_mutagen
        volume:
          nocopy: true
      - type: bind
        source: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind: {}
      - type: bind
        source: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased/.git
        target: /var/www/html/.git
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-pagebased-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      TZ: Europe/Berlin
      VIRTUAL_HOST: pagebased.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-xhgui:v1.25.1
    labels:
      com.ddev.approot: /Users/JensS/CodeProjects/TYPO3Extensions/pagebased
      com.ddev.site-name: pagebased
    networks:
      ddev_default: null
      default: null
    restart: "no"
    x-ddev:
      describe-url-port: 'Launch: ddev xhgui'
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-pagebased_default
    labels:
      com.ddev.platform: ddev
volumes:
  database:
    name: pagebased-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
  project_mutagen:
    name: pagebased_project_mutagen
    external: true
